### ISSUE TITLE
Metabolite ID links to VMH

### ISSUE THREAD

**Issue by CCThinnes** [ThieleLab/MetaboRePort#3]
The links to the VMH from the current metabolite list links to dead ends on the VMH, leading to empty pages titled 'no metabolite'
<img width="2614" alt="Screenshot 2022-06-16 at 13 14 43" src="https://user-images.githubusercontent.com/52928770/174068007-94a55a05-f38c-41d9-9e06-49f88d4a987b.png">
.

**Comment by ThieleLab** [comment]
fixed. IT
